### ISSUE TITLE
Currency conversion not working for basic currencies (exchangeratehost ones)

### ISSUE THREAD

**Issue by alythobani** [biati-digital/alfred-calculate-anything#133] opened 2023-09-29 19:34 UTC
**Are you using the latest version of the workflow?**
Yes

**Have you installed the workflow dependencies?**
Yes

**Describe the bug**
When trying to convert normal currencies (e.g. 60 USD to CAD) the workflow spits out something like:

https://github.com/biati-digital/alfred-calculate-anything/assets/13757215/7bb1e42b-d96a-4623-baaa-94f128e4e216

**To Reproduce**
1. Open Alfred
1. Type '60 usd to cad'
2. See error

**Expected behavior**
Spits out the normal output

**Debug Output**

```
[12:29:48.642] Logging Started...
[12:30:00.810] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument ''
[12:30:00.841] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:00.845] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:00.881] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0'
[12:30:00.912] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:00.914] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.007] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 '
[12:30:01.039] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.041] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.189] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 u'
[12:30:01.244] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.246] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.355] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 us'
[12:30:01.408] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.414] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.443] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd'
[12:30:01.479] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.484] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[{"title":"60 USD","subtitle":"1 USD = 1 USD","arg":60,"icon":{"path":"flags\/USD.png"},"mods":{"cmd":{"valid":true,"arg":60,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":1,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}]}
[12:30:01.553] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd '
[12:30:01.588] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.595] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[{"title":"60 USD","subtitle":"1 USD = 1 USD","arg":60,"icon":{"path":"flags\/USD.png"},"mods":{"cmd":{"valid":true,"arg":60,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":1,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}]}
[12:30:01.673] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd t'
[12:30:01.709] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.716] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.753] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd to'
[12:30:01.788] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.795] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.805] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd to '
[12:30:01.837] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.843] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.888] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd to c'
[12:30:01.919] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:01.927] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:01.988] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd to ca'
[12:30:02.020] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:02.029] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[]}
[12:30:02.078] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd to cad'
[12:30:02.109] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:02.117] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[{"title":"Updating rates...","valid":false,"arg":""}],"rerun":0.2,"variables":{"rerun":true}}
[12:30:02.317] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Queuing argument '0 usd to cad'
[12:30:02.568] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script with argv '(null)' finished
[12:30:02.578] Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] {"items":[{"title":"You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]","valid":false,"arg":""}],"rerun":false,"variables":{"rerun":true}}
[12:30:02.578] WARNING: Calculate Anything[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9AD17C5A-928A-4E69-B9E3-B4E80FA487D3%3E6B6A13A8-C671-4033-A793-EE772BA1FB48)] Script rerun of 0.00 is out of range (0.1s to 5s), rerun will be ignored
```

**System information:**
 - OS: Mac OS 12.5
 - Alfred Version 5
- PHP Version - PHP 8.1.9 

**Additional information:**

I don't use/need the Fixer API as described [here](https://github.com/biati-digital/alfred-calculate-anything#currency-api-key-not-required-but-will-provide-a-lot-more-currencies)

**Comment by biati-digital** [comment] 2023-09-30 05:25
this is a duplicate of #131 exchangeratehost  now requires an API key and will be removed from the workflow

**Closed by biati-digital** 2023-09-30 05:25 UTC
