### ISSUE TITLE
Time keyword not working

### ISSUE THREAD

**Issue by CaptainMalReynolds** [biati-digital/alfred-calculate-anything#86] opened 2022-12-28 01:47 UTC
If you have a problem with the workflow please answer the following questions.

**Are you using the latest version of the workflow?**
3.5.0

**Describe the bug**
When I type "time" nothing happens, and if I open debug section the error( below)

**To Reproduce**
Just type "time " and some words. I'm using Mac OS 12.6.2 with the latest PHP installed. 

**Expected behavior**
Time should work

**Debug Output**
`PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /alfred/Alfred.alfredpreferences/workflows/user.workflow.D2E8101D-9939-47D5-B7F0-E41792F88EF4/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 1253
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /alfred/Alfred.alfredpreferences/workflows/user.workflow.D2E8101D-9939-47D5-B7F0-E41792F88EF4/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 1262
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /alfred/Alfred.alfredpreferences/workflows/user.workflow.D2E8101D-9939-47D5-B7F0-E41792F88EF4/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2482
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /alfred/Alfred.alfredpreferences/workflows/user.workflow.D2E8101D-9939-47D5-B7F0-E41792F88EF4/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2607
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /alfred/Alfred.alfredpreferences/workflows/user.workflow.D2E8101D-9939-47D5-B7F0-E41792F88EF4/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 2619
[20:44:04.983] Calculate Anything[Script Filter] Deprecated: Using ${var} in strings is deprecated, use {$var} instead in alfred/Alfred.alfredpreferences/workflows/user.workflow.D2E8101D-9939-47D5-B7F0-E41792F88EF4/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 1253

**System information:**
 - OS: [Mac OS 12.6.2]
 - Alfred Version 5.0.3
- PHP Version - 8.2.0

**Additional context**

**Comment by biati-digital** [comment] 2023-02-01 22:38
Yes, this is related to a dependency the workflow uses. To be honest, there's been several issues with composer and other dependencies as they define a required PHP version, this sucks because the the main workflow code should work with even PHP 7 (released in 2015) which in older versions of macOS it's included by default but there's been other issues related to this and it's terrible for the users to be forced to install a specific version.

I'm planning to remove composer and external dependencies in the next update.

**Comment by biati-digital** [comment] 2023-02-01 22:40
btw @arvidbjorkstrom thank's for the PR but this will continue to happen unless we remove those dependencies

**Comment by archetyped** [comment] 2023-02-02 03:41
Looking forward to a fix for this, as older versions of PHP that did work with this workflow (e.g. v7.4) can no longer be installed with Homebrew.

This is what you get when running `brew install php@7.4`:

```bash
Error: php@7.4 has been disabled because it is a versioned formula!
```

**Comment by arvidbjorkstrom** [comment] 2023-02-02 07:00
> btw @arvidbjorkstrom thank's for the PR but this will continue to happen unless we remove those dependencies

The pull request I referenced isn’t mine. But the Carbon dependency can be updated to a version supporting PHP 8 I believe?

But I agree, with this being tricky.
There might be more dependencies that conflict with PHP 8, I haven’t checked.
And some of the updated ones supporting PHP 8 might not support older versions of PHP so someone might be stuck with errors whatever is done.

**Comment by biati-digital** [comment] 2023-02-02 07:24
Ohh, sorry @arvidbjorkstrom i thought it was your PR. Yes, that dependency can be updated easily but like i mentioned, this workflow should work with old PHP versions and Alfred 4/5 the only reason it's having problems it's because of the dependency it uses for time calculations. 

It was easier to avoid errors when the workflows did not use composer as the user was able to just run `brew install php` without having to worry about the version installed or having to install updates a few months later. One dependency installs other dependencies and each one requires a different minimum PHP version and if i update a dependency other dependencies are updated and now they require a newer PHP version, etc.

Anyway, i'm looking a way to remove composer and finish the update for Alfred 5

![CleanShot 2023-02-02 at 01 23 41](https://user-images.githubusercontent.com/1219228/216258496-30836fc6-697f-4e07-9e08-e215f7fd1e53.png)

**Comment by arvidbjorkstrom** [comment] 2023-02-02 07:59
Composer should take into account the PHP version the user is running when installing, so maybe a solution would be to not include a lock-file, and let composer do the heavy lifting.

Short of writing your own time library I don’t see how not using composer would solve compability with different versions of PHP?

**Comment by arvidbjorkstrom** [comment] 2023-02-02 08:18
Version 3.5 of the time library includes Carbon both Carbon 1 and 2 so making that a dependency and removing the lock file could fix compatability with different versions of PHP

**Comment by biati-digital** [comment] 2023-02-02 09:05
@arvidbjorkstrom thank's for checking, you are right, the time library 3.5 includes Carbon 1 and 2, i was under the idea that Carbon dropped support for older PHP versions and required PHP8+, surprisingly it supports really old PHP versions. 

it's been a while since i worked on the workflow so i need to check the code. We will use version 3.5 and remove the lock file and that should fix this problem.

**Comment by biati-digital** [comment] 2023-03-19 02:10
This should be fixed in the latest version [4.0.0](https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.0). Please read the release to see what's new.

**Comment by biati-digital** [comment] 2023-03-20 21:20
We'll it appears that the Carbon version included in 3.5 in has a bug with PHP 8.2, i'm starting ti hate dependencies on this project.

**Comment by biati-digital** [comment] 2023-03-23 06:18
A new update has been released [4.0.1]( https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.1) this one should finally fix the time keyword.

**Comment by austinarbor** [comment] 2023-03-24 00:46
confirmed it seems to be working for me now with php 8.4.2

**Comment by biati-digital** [comment] 2023-03-24 03:38
Great, I'll close this issue now.

**Closed by biati-digital** 2023-03-24 03:38 UTC
