### ISSUE TITLE
Currency converter doesn't work properly

### ISSUE THREAD

**Issue by Holovin** [biati-digital/alfred-calculate-anything#102] opened 2023-03-20 13:51 UTC
**Are you using the latest version of the workflow?**
Yes

**Describe the bug**
Currency converter doesn't convert some currencies, when we specify only 1 currency (like 100 USD or 100 EUR, but not 100 USD to EUR).

Examples at v4:
![image](https://user-images.githubusercontent.com/5501086/226357822-ac52397f-32a7-41e0-b3f3-1a10a2bb19a7.png)
↑↑↑ There is no any convertation for some reason

![image](https://user-images.githubusercontent.com/5501086/226357814-6d60d673-539e-4a7f-bdca-fd7cb46dc77e.png)
![image](https://user-images.githubusercontent.com/5501086/226357799-1106cd9d-7cd6-45f7-b4a8-16e199d89943.png)

Examples at v3.5:
![image](https://user-images.githubusercontent.com/5501086/226358753-160cfb99-853c-41fb-b358-85339f795022.png)
↑↑↑ There is same convertation, but work good

![image](https://user-images.githubusercontent.com/5501086/226358745-b18a4f1f-f405-4557-bfc0-d8b5ddd66d6b.png)
![image](https://user-images.githubusercontent.com/5501086/226358736-fe988a2f-2f6e-49b8-a38f-1e70fe9d9a30.png)

**To Reproduce**
0. (currency settings for both vesrions was "USD, EUR")
1. Open Alfred '...'
1. Type '100 USD'
2. See different behaviour

**Expected behavior**
Same correct behaviour as at 3.x versions.

**Debug Output**
Debug from v4 (incorrect behaviour):
`
[14:51:01.214] Calculate Anything[Script Filter] Queuing argument ''
[14:51:01.250] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:01.254] Calculate Anything[Script Filter] {"items":[]}
[14:51:01.370] Calculate Anything[Script Filter] Queuing argument '0'
[14:51:01.411] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:01.416] Calculate Anything[Script Filter] {"items":[]}
[14:51:01.493] Calculate Anything[Script Filter] Queuing argument '00'
[14:51:01.521] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:01.522] Calculate Anything[Script Filter] {"items":[]}
[14:51:01.742] Calculate Anything[Script Filter] Queuing argument '00 '
[14:51:01.782] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:01.788] Calculate Anything[Script Filter] {"items":[]}
[14:51:02.037] Calculate Anything[Script Filter] Queuing argument '00 U'
[14:51:02.100] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:02.104] Calculate Anything[Script Filter] {"items":[]}
[14:51:02.143] Calculate Anything[Script Filter] Queuing argument '00 US'
[14:51:02.180] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:02.184] Calculate Anything[Script Filter] {"items":[]}
[14:51:02.195] Calculate Anything[Script Filter] Queuing argument '00 USD'
[14:51:02.223] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:51:02.225] Calculate Anything[Script Filter] {"items":[{"title":"100 USD","subtitle":"1 USD = 1 USD","arg":100,"icon":{"path":"flags\/USD.png"},"mods":{"cmd":{"valid":true,"arg":100,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":1,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}}]}
`

Debug from v3.5 (correct behaviour):
`[14:49:01.604] Calculate Anything[Script Filter] Queuing argument ''
[14:49:01.646] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:01.650] Calculate Anything[Script Filter] {"items":[]}
[14:49:01.718] Calculate Anything[Script Filter] Queuing argument '0'
[14:49:01.758] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:01.763] Calculate Anything[Script Filter] {"items":[]}
[14:49:01.841] Calculate Anything[Script Filter] Queuing argument '00'
[14:49:01.868] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:01.873] Calculate Anything[Script Filter] {"items":[]}
[14:49:02.081] Calculate Anything[Script Filter] Queuing argument '00 '
[14:49:02.128] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:02.134] Calculate Anything[Script Filter] {"items":[]}
[14:49:02.300] Calculate Anything[Script Filter] Queuing argument '00 U'
[14:49:02.359] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:02.365] Calculate Anything[Script Filter] {"items":[]}
[14:49:02.378] Calculate Anything[Script Filter] Queuing argument '00 US'
[14:49:02.416] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:02.421] Calculate Anything[Script Filter] {"items":[]}
[14:49:02.429] Calculate Anything[Script Filter] Queuing argument '00 USD'
[14:49:02.457] Calculate Anything[Script Filter] Script with argv '(null)' finished
[14:49:02.462] Calculate Anything[Script Filter] {"items":[{"title":"100.00 USD","subtitle":"1 USD =  1.00 USD","arg":"100.00","icon":{"path":"assets\/flags\/USD.png"},"mods":{"cmd":{"valid":true,"arg":100,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":1,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}},{"title":"93.72 EUR","subtitle":"1 USD =  0.94 EUR","arg":"93.72","icon":{"path":"assets\/flags\/EUR.png"},"mods":{"cmd":{"valid":true,"arg":93.72,"subtitle":"Action this item to copy the amount with no format"},"alt":{"valid":true,"arg":0.94,"subtitle":"Action this item to copy the value of 1 to the clipboard"}}},{"title":"A new update of this workflow is available","subtitle":"Press return to install the update","valid":true,"arg":"update","icon":{"path":"assets\/update.png"},"variables":{"action":"update"}}]}`

**System information:**
 - OS: MacOS 13.2.1
 - Alfred Version: 5.0.6
- PHP Version: 7.4.33

**Additional context**

**Comment by Holovin** [comment] 2023-03-20 20:26
Actually my config didn't parsed at all. I've added manually same currencies and result you see at screenshots above.

**Comment by biati-digital** [comment] 2023-03-20 20:40
![CleanShot 2023-03-20 at 14 37 05](https://user-images.githubusercontent.com/1219228/226460396-da7dbe6a-a2a3-49f8-95a3-8c8797a1c0c3.png)

I still don't know if you are using Alfred 5 or 4, i can not see your config so i'm simply guessing. I tried with a few computers and other users also tested this and never saw this problem so without more info the only thing i can think of is that you try to configure it again?

**Comment by Holovin** [comment] 2023-03-20 20:57
I use Alfred 5 (Alfred Version: 5.0.6) as I mentioned before in ticket description.
Ok, I'll try to cleanup and setup again.

**Comment by Holovin** [comment] 2023-03-20 21:04
Seems I found the problem. If I specify this settings...
![image](https://user-images.githubusercontent.com/5501086/226464845-b4195ba6-68f3-4f96-a5f4-8faa4b2cfae0.png)

...it broke converation:
![image](https://user-images.githubusercontent.com/5501086/226464947-758a0e67-ea92-410b-91c7-a435e06e582a.png)

---

So, any first currency in the settings list begin to break conerations. For example I've swap USD and EUR in settings:
![image](https://user-images.githubusercontent.com/5501086/226465505-8564d0b7-4567-43bf-9bbf-3563a3b3d78c.png)

...and now it works:
![image](https://user-images.githubusercontent.com/5501086/226465450-c39901cd-d272-4a1c-833e-511590ee161c.png)

...but now it's break 1st currency in the settings list (EUR):
![image](https://user-images.githubusercontent.com/5501086/226465634-9df09f64-a87f-44b2-80d2-fc26c60062a5.png)

**Comment by biati-digital** [comment] 2023-03-20 21:13
Ohh yeah, the problem is that the workflow first checks if the conversion is **from and to the same target** and stops the execution, in this case the first conversion becomes "USD to USD" so the workflow will stop and return the value you entered `100` it will not process the other currencies. This check has existed since version 1.0.0 where the option to define default currencies did not exist. In a future update i'll improve that part.

Thank's for finding the problem.

**Comment by biati-digital** [comment] 2023-03-23 06:18
This has been fixed in [4.0.1]( https://github.com/biati-digital/alfred-calculate-anything/releases/tag/4.0.1)
![CleanShot 2023-03-23 at 00 17 32](https://user-images.githubusercontent.com/1219228/227119831-7f7a1e50-af97-4a31-9492-c959ad4a023a.png)

**Closed by biati-digital** 2023-03-23 06:18 UTC
