### ISSUE TITLE
Unable to

### ISSUE THREAD

**Issue by layasamadhi** [biati-digital/alfred-calculate-anything#48] opened 2021-08-18 17:08 UTC
Hello.
I don't understand this problem. Do you know something about it?

![CleanShot 2021-08-18 at 19 07 51@2x](https://user-images.githubusercontent.com/6170216/129941762-794f0804-f81a-403d-9671-09f6e0b66f87.png)

**Comment by biati-digital** [comment] 2021-08-18 23:17
Duplicate of #45

**Closed by biati-digital** 2021-08-18 23:17 UTC
