### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted 

### ISSUE THREAD

**Issue by zenminimalist** [biati-digital/alfred-calculate-anything#38] opened 2021-05-29 15:51 UTC
No matter what I try to calculate with CA, it will not work. According to the error long below.

```
[17:47:04.679] ERROR: Calculate Anything[Script Filter] Code 255: Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/XXXXDropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.15EFA02D-86C3-474A-81FB-FF5986D872B7/alfred/Alfred.php on line 48
[17:47:04.679] ERROR: Calculate Anything[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/XXXX/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.15EFA02D-86C3-474A-81FB-FF5986D872B7/alfred/Alfred.php on line 48

```
it has something to do with my Dropbox. Does anyone have an idea what it could be? I tried restarting Alred, reinstalling CA etc. same error.

**System information:**
 - OS: Mac OS 11.4
 - Alfred Version 4.3.4
- PHP Version PHP 7.3.24

**Comment by biati-digital** [comment] 2021-05-29 23:00
Duplicate of #32

**Closed by biati-digital** 2021-05-29 23:00 UTC
